"""Make student academic session required

Revision ID: 83a9314a3724
Revises: e8055676df15
Create Date: 2026-08-19 16:56:46.926856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a9314a3724'
down_revision: Union[str, Sequence[str], None] = 'e8055676df15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'academic_session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'academic_session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
